# Generated by Django 4.2.5 on 2023-09-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('notes', models.TextField(max_length=100)),
                ('location', models.CharField(max_length=30)),
                ('attendees', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
