# Generated by Django 4.2.5 on 2023-09-06 06:25

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='bray', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
