# Generated by Django 4.2.5 on 2023-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='names',
            field=models.JSONField(default={'john': 'john@example.com'}, verbose_name='names'),
        ),
    ]
