# Generated by Django 4.2.5 on 2023-09-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
