# Generated by Django 4.2.5 on 2023-09-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_event_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='names',
            field=models.JSONField(default={'names': ['John', 'Michael', 'Gemma', 'Sandra']}, verbose_name='names'),
        ),
    ]
