# Generated by Django 4.2.5 on 2023-09-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Event", "0003_alter_event_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="event",
            name="notes",
            field=models.TextField(max_length=3000),
        ),
    ]
